services:
  spread:
    image: josiahdc/spread:0.3
    build:
      context: .
      dockerfile: services/spread/Dockerfile
    env_file:
      - secrets/mycelium.env
    deploy:
      mode: replicated
      replicas: 3
  symbiosis:
    image: josiahdc/symbiosis:0.3
    ports:
      - "33933:33333"
    build:
      context: .
      dockerfile: services/symbiosis/Dockerfile
    env_file:
      - secrets/mycelium.env
    depends_on:
      - spread
