services:
  graph:
    image: neo4j:5.26.0-community-bullseye
    volumes:
      - mycelium-neo4j-config:/config
      - mycelium-neo4j-logs:/logs
      - mycelium-neo4j-data:/data
      - mycelium-neo4j-plugins:/plugins
    environment:
      - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth_file
    ports:
      - "7474:7474"
      - "7687:7687"
    secrets:
      - neo4j_auth_file
  spread:
    image: josiahdc/spread:0.2
    build:
      context: .
      dockerfile: docker/spread/Dockerfile
    env_file:
      - secrets/mycelium.env
    depends_on:
      - graph
    deploy:
      mode: replicated
      replicas: 1
  symbiosis:
    image: josiahdc/symbiosis:0.2
    ports:
      - "33933:33333"
    build:
      context: .
      dockerfile: docker/symbiosis/Dockerfile
    env_file:
      - secrets/mycelium.env
    depends_on:
      - graph
      - spread

secrets:
  neo4j_auth_file:
    file: secrets/neo4j_auth.txt

volumes:
  mycelium-neo4j-config:
  mycelium-neo4j-logs:
  mycelium-neo4j-data:
  mycelium-neo4j-plugins:
