services:
  graph:
    image: neo4j:5.26.2-community-bullseye
    volumes:
      - mycelium-neo4j-config:/config
      - mycelium-neo4j-logs:/logs
      - mycelium-neo4j-data:/data
      - mycelium-neo4j-plugins:/plugins
    environment:
      - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth_file
    ports:
      - "7474:7474"
      - "7687:7687"
    secrets:
      - neo4j_auth_file
  spread:
    image: josiahdc/spread:0.4
    build:
      context: .
      dockerfile: services/spread/Dockerfile
    environment:
      OPERATION_INSTANCE_COUNT: "3"
      STOP_NODE_THRESHOLD: "10"
    env_file:
      - ~/.pasture/config.env
    depends_on:
      - graph
  symbiosis:
    image: josiahdc/symbiosis:0.4
    ports:
      - "33933:33333"
    build:
      context: .
      dockerfile: services/symbiosis/Dockerfile
    env_file:
      - ~/.pasture/config.env
    depends_on:
      - spread
      - graph

secrets:
  neo4j_auth_file:
    file: ~/.pasture/neo4j_auth.txt

volumes:
  mycelium-neo4j-config:
  mycelium-neo4j-logs:
  mycelium-neo4j-data:
  mycelium-neo4j-plugins: